
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: local
  application:
    name: Library-Management

  datasource:
    url: jdbc:postgresql://localhost:5432/LibraryManagement
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
report:
  location: C:\\Reports\\Monthly\\

keycloak:
  auth-server-url: http://localhost:8083/auth
  realm: library-realm
  resource: library-client
  public-client: true
  credentials:
    secret: library-client-secret


---
spring:
  config:
    activate:
      on-profile: servar
  application:
    name: Library-Management

  datasource:
    url: jdbc:postgresql://192.168.19.100:5432/LibraryManagement
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://192.168.19.100:8761/eureka/

report:
  location: http://192.168.19.100/reports


